version: '3'
services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
    # # Uncomment the following lines when there are dependant containers (e.g. a database)
    # # depends_on:
    # #   - Dependant container